#ifndef MESSAGE_QUEUE_CODES_HPP
#define MESSAGE_QUEUE_CODES_HPP

#define ECGCOLLECTMODULE_MSG_QUE 4011
#define ECGFILTERMODULE_MSG_QUE 4012
#define ECGTRANSFERMODULE_MSG_QUE 4013

#define OXIMETERCOLLECTMODULE_MSG_QUE 4021
#define OXIMETERFILTERMODULE_MSG_QUE 4022
#define OXIMETERTRANSFERMODULE_MSG_QUE 4023

#define BLOODPRESSURECOLLECTMODULE_MSG_QUE 4031
#define BLOODPRESSUREFILTERMODULE_MSG_QUE 4032
#define BLOODPRESSURETRANSFERMODULE_MSG_QUE 4033

#define THERMCOLLECTMODULE_MSG_QUE 4041
#define THERMFILTERMODULE_MSG_QUE 4042
#define THERMTRANSFERMODULE_MSG_QUE 4043

#endif
